### ISSUE TITLE
Internationalization and translations - i18n & L10n

### ISSUE THREAD

**Issue by kenmanheimer** [SpiderOak/SpiderOakMobileClient#485]
We need to internationalize our app, including:
* Identifying the catalog of UI strings for translation
* Incorporate facilities for collecting translations of our UI strings in various languages
* Instrument our templates and static view text so that the user's device language is used, when we have an available translation
* Institute ways to receive contributed translations

We might follow John McLear's instructions in [Adding i18n to a Cordova App](http://mclear.co.uk/2014/02/14/translations-language-i10n-i18n-cordova-phonegap-app/), including using WikiMedia's [TranslateWiki.net](http://translatewiki.net/) open source translation community project to collect translations from our users. !!

**Comment by kenmanheimer** [comment]
The current version of the strings catalog: https://github.com/SpiderOak/SpiderOakMobileClient/blob/issue-486-l10n-bracketing/www/i18n.json

**Comment by kenmanheimer** [comment]
Collateral pending issues:

* #623 "Stay logged in" warning i18n template is broken and breaks the app when viewed
* #624 Need to bracket strings for file types
* Renee reports:
  * Blank text: Long press of My Shares reveals blank menu options
  * Long press of Public shares reveals all menu options blank except Forget
* Need to suppress plethora of useless "No translations available (yet)" that `grunt test` spews

**Comment by reneelynn** [comment]
I cannot recreate #623 although the "{Stay logged in}" words are bracketed as I noted here in the warning message.

**Comment by kenmanheimer** [comment]
b1903048a9b33f603fbde836efc7ec2bfc675bf2 accounts for the {{Stay logged in}} substitution problem, by removing the fragment from the brand customization category and including it among the regular translation candidates. (It turns out that including the string among brand customization strings wasn't the best way to handle it, and our l10n mechanism doesn't provide for substitution strings containing spaces, besides.)

This means that we have a small, but potentially colloquial string: "Stay logged in", which was not provided to the translators for this round of Spanish translations. Google translate provides us with an approximation, "Permanecer conectado", but that seems closer to "Stay connected". That may work, but we're calling on those among us with Spanish-speaking connections to guide us - eg, @chiiph, @reneelynn: what would be the best candidate for us to use for a Latin-American Spanish translation of "Stay logged in"?

**Comment by reneelynn** [comment]
I can't speak for fluency or Latin American Spanish...  "quedese conectado" seems a grammatically correct option if you take into account that my experience is basically entirely with Puerto Rican inlaws.

**Comment by reneelynn** [comment]
warren suggests: Manténgase en sesión

**Comment by reneelynn** [comment]
I just want to clarify here that the only place it was marked in brackets was the warning message, so they probably do have the phrase because it was written normally in the login page and in the settings section.

**Comment by kenmanheimer** [comment]
Warren suggests `Manténgase en sesión`, similar to what Shanya found at wiktionary (`Mantener mi sesión`). Warren's indicates his suggestion is formal voice, which suits our applications, so this is our likely candidate.

**Comment by kenmanheimer** [comment]
e57484f372eb3ff8c3cbd1b968ee05d32cbf9a75 fixes the ShareRoom long press menu blank items. The technique could use review - see the commit notes for details.

While looking for similar situations in action items, I didn't find the same arrangement elsewhere, but did notice some overlooked source phrases in other action item descriptions, which I corrected in c5d6d4fda5211766af65297ec395fc5d6017a093 and which adds a few more strings for which we need additional translations:

- Share file
- Open in

Lastly (for this comment), having noticed some blithely missed phrases, I realize we could use another preliminary QA  review, with all the translated phrases highlighted so ones not being translated can be spotted, so we're ready with ad hoc translations when the bulk of translations from the contracted company comes in. The highlighting could easily be done by doing a build while the translation routine is rigged to bracket the translations with distinctive characters.
