### ISSUE TITLE
Wrong error message for failed login

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#614]
Logins with a dc1 account I got "Authentication error Incorrect ShareID or RoomKey" - wrong & confusing error message. https://treehouse.spideroak.com/cs/admin/avatar/983953/ for the account.

I am using the correct login credentials; they work for the desktop client.

3.1.2RC1

**Comment by kenmanheimer** [comment]
I happened to notice that "Incorrect ShareID or RoomKey" error happens on failed login attempts when providing a username for a non-existent account, but not on login attempts with a valid account username but incorrect password. Identifying the specific condition is helpful, while also reinforcing how off the error message is.
