### ISSUE TITLE
"Stay logged in" warning i18n template is broken and breaks the app when viewed

### ISSUE THREAD

**Issue by devgeeks** [SpiderOak/SpiderOakMobileClient#623]
https://github.com/SpiderOak/SpiderOakMobileClient/blob/aa79813a2bff218ffa08a70dba4b55cd6a6b40a9/tpl/rememberMeWarningViewTemplate.html#L5

This displays with the [[Stay logged in]] displayed as {{Stay logged in}} (complete with curly braces).

If you see this cursed screen, it then breaks many things once you are in the app including the backbutton behaviour. O_o

**Comment by devgeeks** [comment]
Actually, the backbutton thing might be an error unto itself.

Something to do with: https://github.com/SpiderOak/SpiderOakMobileClient/blob/aa79813a2bff218ffa08a70dba4b55cd6a6b40a9/src/helpers/FileDownloadHelper.js#L81

**Comment by devgeeks** [comment]
The backbutton thing was unrelated and fixed in c46b4a1

**Comment by kenmanheimer** [comment]
The bracketing substitution is being handled in #485 - see https://github.com/SpiderOak/SpiderOakMobileClient/issues/485#issuecomment-69089585
