### ISSUE TITLE
Need to bracket strings for file types

### ISSUE THREAD

**Issue by devgeeks** [SpiderOak/SpiderOakMobileClient#624]
e.g.: https://github.com/SpiderOak/SpiderOakMobileClient/blob/issue-486-l10n-bracketing/src/helpers/FileHelper.js#L10

Not actually sure how we are going to do this, since it is also created before `qq()` exists... 

Maybe what we actually need is to modify it. Instead of being a static `return FILETYPE_WORDDOC;`, it could be a function that can then use `qq()` to get a translation and return the file info?

**Comment by kenmanheimer** [comment]
Implemented in ae8ab8f60dd8bc55bd5eb5bf6d12739b84ebc6aa, as part of #485.

**Comment by kenmanheimer** [comment]
Fixed with #485
