### ISSUE TITLE
test build asks to enter "new" passcode when turning passcode off

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#625]
Should say "current" like Blackphone 2.1.4 (and I assume Blue and Orange 2.1.4 do - Blue is having server issues at the moment so I can't verify).

**Comment by kenmanheimer** [comment]
Good catch - fixed in 17233e2e8d40a577cbd39c783332362528969c66 and 6957b4df00560a410dc4d6fe6f05efba5f8b4bf7 (yeah, two commits for two edits to the same string - oy).

**Comment by reneelynn** [comment]
Still in the latest build I got

**Comment by reneelynn** [comment]
Actually, only in Spanish. It's corrected in English, both Australia and USA

**Comment by kenmanheimer** [comment]
The disable-passcode message has been fixed, along the way, and reads in the current version: "Ingresa tu código de acceso de 4 dígitos" ~= "Enter your 4-digit access code".
