### ISSUE TITLE
SpiderOak___ vs SpiderOak ___

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#634]
BBQ187 basically they want the last part separated for BP so that the text wrapping is nicer. I think we discussed this before and said no, but they re-pinged me on it and I couldn't find an original ticket for it.

**Comment by reneelynn** [comment]
Tommy I was told this question needed to go to you - let me know if you need more details and I'll send you the copy from BBQ

**Comment by reneelynn** [comment]
ping

**Comment by devgeeks** [comment]
I'll try to make sure this happens in the next version we send to them

**Comment by reneelynn** [comment]
ok, Matt said it's not a huge concern... I just need to give them some sort of update

**Comment by devgeeks** [comment]
I have a PR ready that should fix this (at least on Android, where it matters), but it needs a lot of testing.

**Comment by reneelynn** [comment]
I will let them know
