### ISSUE TITLE
Phase out account username for email

### ISSUE THREAD

**Issue by kenmanheimer** [SpiderOak/SpiderOakMobileClient#635]
* SpiderOak is going to be changing to use account email as the primary identifier, transparently generating what is now serving as the username.
  * The switchover is due Jan 28!
* Though it wasn't prominently known, the email has always been accepted in the Username field.
* Since those with new accounts won't know their account usernames, only their account emails, we need change the app to direct them to use their email for login
  * We can prompt for "Email or username", where there's space, for a few releases.
  * We should prompt for Email, but provide some help info that username could be used ("and learn which email you used for your account, via the settings, for next time")
* We also need to present the email in the Settings account information
* And where else?

**Comment by reneelynn** [comment]
The standardization that was decided on was "email/username" in that order as the prompt. Worth discussing if this does not fit in mobile app.
