### ISSUE TITLE
"Blue" custom templates not localized

### ISSUE THREAD

**Issue by devgeeks** [SpiderOak/SpiderOakMobileClient#646]
* https://github.com/SpiderOak/SpiderOakMobileClient/blob/master/custom/brands/Blue/tpl/aboutSpiderOakViewTemplate.html
* https://github.com/SpiderOak/SpiderOakMobileClient/blob/master/custom/brands/Blue/tpl/needAnAccountViewTemplate.html

Both of the above have not been bracketed for localization.

**Comment by kenmanheimer** [comment]
It looks like I can adapt the localizations for the standard aboutSpiderOakViewTemplate.html to produce adjusted ones for the Blue version.

It also looks like there is even less to account for in the differences between the Blue and Orange versions of the needAnAccountViewTemplate.html. Actually, it looks like the only differences are not necessary.

Specifically, unless I'm missing something, changing to the standard version would change:

> In order to ensure 'Zero-Knowledge' Privacy, your account must be  created on a computer. Please go to ~spideroak.com~ to signup and then you can return to the SpiderOak mobile app for use.

to:

> In order to ensure 'Zero-Knowledge' Privacy, your account must be created on a computer. Please go to ~spideroak.com~ and follow the instructions to establish your account.

(The second sentence in both is omitted on iOS, and suitable substitutions are done for ~spideroak.com~, etc.)

It seems like the latter is as good as the former, and we could just use the Orange template, eliminating one of the Blue brand-specific templates.

Am I missing something? Here are the respective versions of that template:

* [Orange](https://github.com/SpiderOak/SpiderOakMobileClient/blob/master/tpl/needAnAccountViewTemplate.html)
* [Blue](https://github.com/SpiderOak/SpiderOakMobileClient/blob/master/custom/brands/Blue/tpl/needAnAccountViewTemplate.html)

**Comment by devgeeks** [comment]
Sounds good to me...
