### ISSUE TITLE
Client report: Device doesn't show in mobile

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#657]
avatar: 494593
OS: Windows
Mobile: iOS (both an ipad and an iphone running 8.1.1

Device Alex E6530 Laptop does not load in mobile. (Error - Network Timeout (status: 0).) It does load in web, but takes 1-3 minutes to show up whereas their other device (Susan E6500 Laptop) shows up more or less immediately in web and also shows no problem in mobile. User also reports space reporting is different in the two devices, but that's more or less something we're used to seeing.

I originally thought it might be related to https://treehouse.spideroak.com/pandora/ticket/6157 but since this user CAN see devices in web, I'm starting to doubt it. 

https://spideroak.zendesk.com/agent/tickets/589029

**Comment by reneelynn** [comment]
DKrow's original troubleshooting notes:

>Spider logs:

>2014-11-23 23:10:50,039 ERROR initialize_app oak did not connect in the specified interval of 360 seconds
2014-11-23 23:10:50,039 INFO spider Quitting...
2014-11-23 23:10:50,039 INFO Network application_shutdown
2014-11-23 23:10:50,039 DEBUG dispatch proxy sender name 'oak'
2014-11-23 23:10:50,039 DEBUG twisted (TCP Port 49255 Closed)
(This might be nothing, but I thought I'd include it)

>2014-11-24 14:20:29,862 DEBUG spider purge_single_journal_entry called
2014-11-24 14:20:29,862 ERROR spider Cannot exclude c:\icons.position: not included
2014-11-24 14:20:29,862 WARNING spider purge_single_journal_entry ValueError(u'Cannot exclude c:\icons.position: not included',)
2014-11-24 14:20:29,862 DEBUG Pandora.purge request: j:494593-1-33286 f:u'icons.position' @ 1380473530 v:494593-1-234271 sj:-

>(nothing here sounds like issues viewing files)

>I am only seeing lag errors in Oak.

>I don't see anything in the logs that indicates the user's issues. I'm holding off on assigning you a due date on this since I don't see anything helpful.

**Comment by merickson** [comment]
The fact that it takes 1-3 minutes consistently would indicate something server-side to me with the device. It just may be timing out on the mobile client here.

**Comment by reneelynn** [comment]
What would cause that? DZ says there are no ongoing server issues in Trac 6157

**Comment by reneelynn** [comment]
User gave some more info: "in accessing my device Sue E6500 Laptop each screen refresh as I'm drilling down the folders to the file I may need only takes 3-5 seconds on both iPhone/iPad and Web. I ran another test this morning from the Web to access a folder on device Alex E6530 Laptop and it took 2 minutes and 42 seconds to access a folder (my download speed on my PC is over 100mbs down and 50mbs up)."

**Comment by reneelynn** [comment]
ping

**Comment by reneelynn** [comment]
ping

**Comment by devgeeks** [comment]
@reneelynn 

Seems like this is the most relevant:

> I ran another test this morning from the Web to access a folder on device Alex E6530 Laptop and it took 2 minutes and 42 seconds to access a folder

As @merickson said, I am not sure we can do much on the mobile side apart from increasing the timeout. This feels like an issue with their account or something fairly specific to their account.

**Comment by reneelynn** [comment]
closing in favor of Internal issue 6947
