### ISSUE TITLE
Can't log in with newest build

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#661]
3.2.0-68-gf713d88

Incorrect username/pass errors with correct username+pass and with correct email+pass

**Comment by devgeeks** [comment]
I am not sure I understand the description of the problem. Can you be more verbose?

**Comment by devgeeks** [comment]
Are you saying you can't log in at ALL?

**Comment by reneelynn** [comment]
I am inputting the correct username and pass and also the correct email and pass, but i am getting "incorrect login" errors.

**Comment by devgeeks** [comment]
I can't replicate this. Maybe DM me more sensitive details in IRC

**Comment by devgeeks** [comment]
Is this still a thing?

**Comment by reneelynn** [comment]
nope!
