### ISSUE TITLE
First Login with a given account

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#663]
## Description 
When logging in with an account for the first time, a screen will pop up alerting users that the app is not Zero-Knowledge and giving them the option to continue anyway or abort.

'Zero-Knowlege' should now be formatted as Zero-Knowledge, without the single quotes. 

Test case number: TC65 

Test run: [http://spideroak.testlodge.com/projects/3096/runs/137336?tab=2&run_section_id=68049#executed_case_6977541](http://spideroak.testlodge.com/projects/3096/runs/137336?tab=2&run_section_id=68049#executed_case_6977541)

**Comment by kenmanheimer** [comment]
I think this behavior description is correct, and the behavior is what we intend.

Having new and changed test cases posted to our project issues queue, like this, seems like a good way to arrange for us to review them.

Further, it seems like I can mark the issue as closed, reflecting that it's accepted as proper behavior. Feel free to reopen it if you think there's more to discuss.

**Comment by reneelynn** [comment]
No; the build shows 'Zero-Knowledge' and it should show Zero-Knowledge, without the quotes. see: https://treehouse.spideroak.com/pandora/wiki/Marketing/StyleGuide

**Comment by reneelynn** [comment]
Also the formatting is largely because I'm still playing around with TestLodge's github integration.

**Comment by kenmanheimer** [comment]
Ah - might the issue description have changed after I originally saw it?  I didn't notice the Zero-Knowledge specifics...

**Comment by reneelynn** [comment]
Yep probably :) integration isn't quite working the way I want it to

**Comment by kenmanheimer** [comment]
Cool - thanks. Also incidentally (totally me being defensive (-% ), the style guide actually changed since we were originally told that Zero-Knowledge had to be in single quotes (yuck). I knew about the change, but it slipped between the cracks - glad to get the reminder to change it to what we prefer...
