### ISSUE TITLE
Case sensitive usernames

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#665]
Correct me if I'm wrong but I don't remember usernames being case-sensitive previously, but they definitely are with 3.2.0-85-gdb4898d

**Comment by kenmanheimer** [comment]
This is happening on the server side.

While the website gets case-insensitive logins via the /browse API, which it is supposed to use, we recently switched away from the browse API, to free it up for implementation of cross-site request forgery (XSRF) prevention.. Apparently the direct object-server API does not support case-insensitivity.

@merickson, does this sound correct? Is there documentation for either API that includes details about this behavior?

@merickson, @devgeeks, if this is, indeed, the problem, we need to figure out what to change:
* the direct object server API, to support case-insensitivity
* the app to go back to /browse but with some way around XSRF inhibition
* the requirement for for case-insensitivity
* or something else?

**Comment by kenmanheimer** [comment]
Fixed by #669.
