### ISSUE TITLE
Logins seem broken with email

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#668]
renee+inca@spideroak.com with standard QA pass will log in online but not in mobile app. QAten with the same pass logs in fine.

**Comment by devgeeks** [comment]
This smells of being caused by the switch away from `/browse` (much like the case sensitivity issue for usernames).

Can you confirm if it is login via email address that is the issue, or that email address specifically?

**Comment by reneelynn** [comment]
It happens with other email-only test accounts.

**Comment by devgeeks** [comment]
Yeah, I can't log in using my email address on my main account.

**Comment by kenmanheimer** [comment]
Fixed by #669.
