### ISSUE TITLE
Misaligned "Send feedback"

### ISSUE THREAD

**Issue by rebeccawatson** [SpiderOak/SpiderOakMobileClient#672]
Under settings, "send feedback" is a bit far up from center. 

![img_0370](https://cloud.githubusercontent.com/assets/5685302/6704012/59ed2f62-cd00-11e4-8e1c-b604bc01e6de.PNG)

**Comment by rebeccawatson** [comment]
Is it typical to have send feedback right at the top? I feel like people might accidentally click there a lot / get frustrated when they keep popping up their email app on accident.

**Comment by devgeeks** [comment]
Interesting you are specifically calling out "send feedback when *none* of them are in the centre.
