### ISSUE TITLE
"Stay logged in" only works on the specific checkbox and not text

### ISSUE THREAD

**Issue by rebeccawatson** [SpiderOak/SpiderOakMobileClient#685]
On the first login screen, only the little circle responds to clicking - I feel like in the past I was able to click on the "stay logged in" text as well? This is a really small area of selectable space. 
(This is really minor, more of a question of if I'm misremembering it!)

**Comment by devgeeks** [comment]
Not sure if it was like that on the old login screen, but it has never been like that on the new one.

Having said that, I am totally :+1: for this
