### ISSUE TITLE
Missing translation languages

### ISSUE THREAD

**Issue by rebeccawatson** [SpiderOak/SpiderOakMobileClient#696]
Note from Renee: the app successfully translates to French, it even seems grammatically correct, but we haven't been testing for this / didn't know it was a thing. Are there other languages besides Spanish (and now French) to be testing for?

**Comment by reneelynn** [comment]
note that this is iOS only; Android does not translate to French.

**Comment by reneelynn** [comment]
spanish, english uk, portuguese, russian and french and german, says Tommy. Leaving open because I get Spanish in android but not French.

**Comment by reneelynn** [comment]
nope just needed to completely close out of app
