### ISSUE TITLE
Passcode

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#703]
## Description 
Setting a passcode allows for an additional layer of security to access the app. With a passcode, and Remember Me enabled your files are secure, and can be viewed by only the user, and still you have the benefit of caching.

## Expected result 
Each account can have a distinct, four-digit passcode and passcode timeout associated with each device. At specific moments in operation of the application, in order to easily authenticate the user, the application challenges the user to present the passcode.

Those moments are:

Return the application after switching to another one, if the amount of time away has been longer than the selected passcode timeout
Access to most actions that change the passcode
Upon changing the passcode, reentering the new one to confirm that what was entered is what was intended
When the passcode challenge is being used to protect access to a logged in account upon return to the app, the passcode can be bypassed by tapping an X in the upper right of the challenge screen. Upon confirming the bypass the application will logout of the current account and the user will be returned to the application login screen.
Any time that the user attempts to satisfy a passcode challenge and fails, they are presented with a notice of the number of immediately successive failure and that the limit is 5. After five successive failure the application logs out of the current account and returns to the login screen, as with passcode bypass, above.

In either case where the challenge was bypassed, the next time that the logged-out account is logged in (on that device), the user will be notified that they had been logged out due to passcode challenge bypass, and offered the choice of retaining or abandoning their current passcode.

The settings screen has an entry for the account passcode when the account is logged in. The entry indicates whether or not the current account has an assigned passcode.

If the account does not have an assigned passcode, then selecting the item prompts for the passcode and confirmation, and if they're identical then the user is returned to the main settings screen with the passcode indicated active
If the account does have an assigned passcode, then selecting the item prompts the user for the current passcode. If the correct passcode is entered, the user is brought to the passcode details screen.
The passcode details screen:
Turn Passcode Off - if the user satisfies another passcode challenge, then the passcode is deactivated. They are returned to the main settings screen.
Change Passcode - if the user satisfies the passcode challenge, then they are prompted to provide and confirm a new passcode.
Require Passcode - this sets a timeout period within which the user will not be passcode-challenged upon returning to the app after suspending. It defaults to Immediately, and can be set to 1, 5, and 15 minutes, and 1 and 4 hours.
When changing the timeout, the user has to hit the back button to return to the passcode settings screen.

## Other information 
Reported by: Rebecca Watson 

Test case number: TC14 

Test run: [http://spideroak.testlodge.com/projects/3096/runs/142992?tab=2&run_section_id=76801#executed_case_7188812](http://spideroak.testlodge.com/projects/3096/runs/142992?tab=2&run_section_id=76801#executed_case_7188812)

**Comment by reneelynn** [comment]
@rebeccawatson this auto-created from TestLodge integration but you didn't put any feedback in on what actually happened/why it failed.

**Comment by rebeccawatson** [comment]
Ah, the previous ticket #702 I created in GitHub is the Passcode issue in question
