### ISSUE TITLE
Increase cordova-HTTP network timeouts from 1 minute to 5

### ISSUE THREAD

**Issue by kenmanheimer** [SpiderOak/SpiderOakMobileClient#713]
It looks like the switchover to cordova-HTTP (for cert pinning, etc) reduced the network timeout from our jacked-up javascript XHR [setting of five minutes](https://github.com/SpiderOak/SpiderOakMobileClient/blob/3.3.0/src/app.js#L16) to a default value of 1 minute (here's relevant code for the [IOS platform](https://github.com/SpiderOak/cordova-HTTP/blob/SpiderOak/src/ios/AFNetworking/AFURLRequestSerialization.h#L108-L113)). The linked comment suggests how it can be modified for IOS, Tommy found a pending pull request in the cordova-HTTP original fork, wymsee/cordova-HTTP#40, which would provide for setting the timeout on the Android side (or maybe simpler, convey how we could make that change in a more hard-coded way).

**Comment by devgeeks** [comment]
I think our old JS timeout was 3 minutes

**Comment by devgeeks** [comment]
Apparently it was 5.

**Comment by kenmanheimer** [comment]
@devgeeks, is there any reason not to just go with 5 minutes timeout, and to not include it in the next release? Or 3 minutes, if that seems better - but increase it from what it is now, since that seems likely to be causing ShareRoom timeouts incompatible with the web site?

**Comment by devgeeks** [comment]
I agree, I just feel like this release is taking a long time. I will push it up to 5 (though I can't imagine ANYONE sitting there with their phone in their hands waiting 5 minutes for something to load).
