### ISSUE TITLE
App Store Ad

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#714]
## Description 
spideroak.com accessed from any mobile device should have a bar at top advertising (and linking to) the SpiderOak App

## Actual result 
old branding

## Other information 
Reported by: Rebecca Watson 

Test case number: TC48 

Test run: [http://spideroak.testlodge.com/projects/3096/runs/155891?tab=2&run_section_id=98139#executed_case_7731869](http://spideroak.testlodge.com/projects/3096/runs/155891?tab=2&run_section_id=98139#executed_case_7731869)

**Comment by devgeeks** [comment]
This sounds more like a web site issue than a mobile app issue?

**Comment by reneelynn** [comment]
Becca please open this in Trac and then close this ticket.
