### ISSUE TITLE
Login (Remember Me OFF)

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#715]
## Description 
Typed in username and password. App opens directly into SpiderOak Hive.

## Steps to reproduce issue 
Enter Username, [Next] activates
Enter Password, [Previous] & [Go] activate
Login - Spideroak Logo will appear
Enter incorrect password: 3-5 sec error message, fields not cleared
Enter correct password: success

## Expected result 
After 3 minutes of idling the app will sign a user out.

## Actual result 
does not sign out after idling 5+ minutes

## Other information 
Reported by: Rebecca Watson 

Test case number: TC02 

Test run: [http://spideroak.testlodge.com/projects/3096/runs/155891?tab=2&run_section_id=98140#executed_case_7731875](http://spideroak.testlodge.com/projects/3096/runs/155891?tab=2&run_section_id=98140#executed_case_7731875)

**Comment by devgeeks** [comment]
Not sure about this one...

> After 3 minutes of idling the app will sign a user out.

There is no auto sign out. If the app is not quit from the app switcher, it will stay logged in when it resumes...

**Comment by reneelynn** [comment]
Ohman. So this test case apparently never got updated from the original mockups - we've never had idling signouts and I have now updated the test case.
