### ISSUE TITLE
Supported File Types

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#716]
Details view used to have "download" as well as send, link, Favorite, did it not?  It does not have "download" now. 
Title is incorrect: this is true for both supported and non-supported file types in iPad. Not seen in Android.

Reported by: Renee Jackson 

Test case number: TC05 

Test run: [http://spideroak.testlodge.com/projects/3096/runs/156632?tab=2&run_section_id=99840#executed_case_7761173](http://spideroak.testlodge.com/projects/3096/runs/156632?tab=2&run_section_id=99840#executed_case_7761173)

**Comment by reneelynn** [comment]
![img_0307](https://cloud.githubusercontent.com/assets/3867179/8487334/04866cbc-20d1-11e5-9586-ef4c2f653616.jpg)
![img_0750](https://cloud.githubusercontent.com/assets/3867179/8487347/2311caaa-20d1-11e5-82e0-afa11236604d.JPG)

**Comment by devgeeks** [comment]
Oh, on iOS?

iOS has never had "download/save". There is nowhere to save it to.

**Comment by reneelynn** [comment]
Well then.
