### ISSUE TITLE
App Store Ad

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#718]
## Description 
spideroak.com accessed from any mobile device should have a bar at top advertising (and linking to) the SpiderOak App

## Actual result 
ad is blank

## Other information 
Reported by: Renee Jackson 

Test case number: TC48 

Test run: [http://spideroak.testlodge.com/projects/3096/runs/159234?tab=2&run_section_id=104689#executed_case_7869946](http://spideroak.testlodge.com/projects/3096/runs/159234?tab=2&run_section_id=104689#executed_case_7869946)

**Comment by devgeeks** [comment]
The ad on the SpiderOak website has nothing to do with the app itself.

**Comment by reneelynn** [comment]
Sorry, TestLodge automatically creates tickets in this repository for failed tests, meant to grab and close this one before you got to it but got distracted
