### ISSUE TITLE
Remember Me ShareRoom clarification

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#729]
Just to make sure I'm not crazy;

Added a ShareRoom, selected "remember me"
It is not retained on signout.
It is still there when I sign back in to the same account. 

This is expected behavior correct?

**Comment by kenmanheimer** [comment]
Yep, it's the intended behavior.

The ShareRooms you select to "remember" are kept private, not kept around in the roster when you log out.

(Note that, if I recall correctly, any ShareRooms that are selected to be remembered when no account is logged in - you can do that - continue to be remembered when you log in to an account, and when you subsequently log out, until they're deliberately selected to not be remembered. The idea being, that choice is a public one, spanning any logins.)

**Comment by reneelynn** [comment]
that's what I thought, just making sure!
