### ISSUE TITLE
3.5.0 RC2 doesn't update cleanly Android

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#741]
1) Install Android ONE app from Playstore
2) Download and install 3.5.0 RC2 apk
3) End up with both apps
![screen shot 2016-11-16 at 2 55 31 pm](https://cloud.githubusercontent.com/assets/3867179/20365557/e0eb0a42-ac0c-11e6-9a05-ac498cd73ae0.png)

**Comment by reneelynn** [comment]
Went back and checked RC1 of 3.5.0, and it just wouldn't install at all with the old ONE installed, so this is improvement, I guess? We should not be ending up with 2 different versions of ONE; the new version should replace the old one.

**Comment by devgeeks** [comment]
Why did you close this? Is it fixed?

I would assume that something went wrong with one of the Branding scripts not setting the correct identifier for ONE (if I had to guess).

**Comment by reneelynn** [comment]
I think I pressed the wrong button :(

**Comment by reneelynn** [comment]
alright we have a version fixing this!
