### ISSUE TITLE
upload old data cache folder to recover data?

### ISSUE THREAD

**Issue by Goddard** [SpiderOak/SpiderOakMobileClient#755]
Can a cached folder be uploaded to recover lost data?

The cache folder before the computer crashed is about 200 GB.

The computer is gone.

The data was never uploaded for 3 months.

Is the data recoverable from the cache folder?

Thanks

**Comment by wpost** [comment]
That's a question for our support team at support@spideroak.com. Be sure to write from the email address associated with your account and mention the name of the device that uploaded the files you are trying to recover. Also describe the cache you are asking about.

If I understand you correctly (and I might not be), no. The way to recover data is selecting it in the Manage tab of the application and downloading from there. The desktop application is better suited than the mobile client for this, by the way.

**Comment by Goddard** [comment]
So data that is ready to be uploaded is not stored in the cache file?

Support wasn't helpful.  

I know the official way to recover is through the management tab.  I am wondering how the information is stored and how I can decrypt it myself or perform the upload only so I can then go into the management tab and download the information normally since it never uploaded for 3 months, which the software didn't warn me about by the way which in my humble opinion is an epic fail.  The software offered ZERO notifications about anything actually.
